# Generated by Django 2.2 on 2019-04-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_userlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlibrary',
            name='books',
            field=models.ManyToManyField(blank=True, to='books.Book'),
        ),
    ]
